### ISSUE TITLE
Possible bug in Flight Offer Search API

### ISSUE THREAD

**Issue by aavetisyan24** [amadeus4dev/amadeus-code-examples#20]
Hi,
I think there is an issue in flight offer search API.
I'm selecting nonStop as true, however result is showing both direct and stopover flights.
Here is screenshot.
 
![image](https://user-images.githubusercontent.com/66968202/147392779-f569cac1-269b-4697-a7e0-577e4cfa1ff6.png)

**Comment by tsolakoua** [comment]
We tested the API on our side and all flights are direct. 

However, there is one direct flight with arrival in `ONT` as you pointed out. Since the API lets you search flights between two cities, more than one airport can be returned. 

For example, if you search for a flight from NCE to PAR: PAR (city code of Paris) has several airports so they will appear in the response. There are cases such as your API call, where the API can return airports from other regions if they are not too far away from each other.
